### ISSUE TITLE
Обучение первой версии модели

### ISSUE THREAD

**Issue by rrkid** [rrkid/PCI#11]
Обучить первую версию модели с обработанными данными и поместить под версионный контроль DVC.

**Comment by rrkid** [comment]
@mmlofficial  требуемый baseline = 0.7

**Comment by mmlofficial** [comment]
c22753b3936b34df1a86ff6e561f7fa26a5092be
Первая версия модели обучена
score на train_test_split - 0.8195872933605524
score val - 0.7925078235522125
score train - 0.8846435572561174
