### ISSUE TITLE
Новый способ обработки текста

### ISSUE THREAD

**Issue by mmlofficial** [rrkid/PCI#17]
Предлагаю обработать текст следующим образом : 
Все русские символы убрать из текста и оставить исключительно допустимые спец. символы цифры и английские буквы.

**Comment by mmlofficial** [comment]
Также написать тесты для проверки функции

**Comment by sticktoless** [comment]
Изменены уже существующие тесты в коммите 1750ee340ef1c57946bf107d66a18b3ee74664f7

**Comment by sticktoless** [comment]
Изменена функция обработки строки в соответствии с требованиями (коммит a758086b38597eb388a0338e17ef664fe33727a3)

**Comment by mmlofficial** [comment]
1. Создать новую ветку
2. Создать новые тесты
3. Изменить travis.yml
4. Создай новую функцию обработки в новой ветке
5. В функции заменить цифры прописанные буквами на цифры написанные цифрами
6. Обработать данные и поставить под dvc

**Comment by mmlofficial** [comment]
Исправить тесты. Новый файл string_parser должен называться string_parser_pro!

**Comment by mmlofficial** [comment]
Требуется вернуть старый файл string_parser и переименовать новый в string_parser_pro.

**Comment by mmlofficial** [comment]
2265e3cde4fdb75f4abb9d65b74f69ebd7cac890
Изменена функция в соответствии с требованиями

**Comment by mmlofficial** [comment]
2a507649941abd2769ff1bd9255f63e76e6a066b
Файлы обработаны новой функцией и помещены под версионный контроль
