### ISSUE TITLE
Настройка CI

### ISSUE THREAD

**Issue by rrkid** [rrkid/PCI#5]

**Comment by mmlofficial** [comment]
eae2106496bbeaf4b20675a33c2731ebe92bce2c

**Comment by mmlofficial** [comment]
Изменен путь к файлу тестов для Travis CI

**Comment by mmlofficial** [comment]
Подготовить скрипт для модульного тестирования функции "prepareString". Расположить по следующему пути "/tests/test.py".

**Comment by sticktoless** [comment]
Добавил модуль для тестирования функции prepareString в коммите 67718e301c962488a311bca954892b8fef8c454d
