### ISSUE TITLE
Написать функцию prepareString

### ISSUE THREAD

**Issue by rrkid** [rrkid/PCI#6]
Написать функцию "prepareString" для обработки входной строки данных. 
Вход: строка
Выход: обработанная строка по следующим правилам

- удалены все разделители, спецсимволы

- буквы привести к нижнему регистру 

- слова в строке должны быть разделены одинарным пробелом

**Comment by sticktoless** [comment]
Добавлен модуль с функцией prepareString в коммите 3a8793c17550ce4c2e4e1f0ad06fe79a29d8f741
